name: Deploy til terapisomvirker.no/b22 via FTP
#test om denne godtar is som betaling 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Hent repoet
        uses: actions/checkout@v3

      - name: Last opp til FTP-server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.terapisomvirker.no
          username: git@terapisomvirker.no
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.github/*
            README.md
